### ISSUE TITLE
Keys that are only used on conditional translations are always treated as missing keys

### ISSUE THREAD

**Issue by grackeon** [romanrostislavovich/ngx-translate-lint#146]
# Bug report

## Describe the bug

If a translation key is only used in cases, where it depends on a condition if the key is used, the linting treats the key as missing.

**ngx-translate-lint@1.11.0** works fine.
**ngx-translate-lint@1.20.4** shows error that keys don't exist in project.

## To Reproduce

- Include a conditional translation key in a view, for example like: `<div>{{(condition ? 'myKey1' : 'myKey2')|translate}}</div>`
- Add `myKey1` and `myKey2` to translation file.
- Run `ngx-translate-lint --keysOnViews disable -l <path-to-languages> -p <path-to-views>`
- Lint will fail with: `Key: 'myKey1' doesn't exist in project'` and `Key: 'myKey2' doesn't exist in project'`

## Expected behavior

Keys that are used under certain conditions should not count as missing.

**Comment by svoboda-rabstvo** [comment]
Hi @Moritz1409 thanks for quick answer, :) I try to resolve your issue without this flag in the future. 

Have a nice day
