### ISSUE TITLE
Found too many zombies in the new Angular 17 control flow

### ISSUE THREAD

**Issue by pingouin-creation** [romanrostislavovich/ngx-translate-lint#154]
# Bug report

## Describe the bug

The linter still works, but all keys inside a @if or @for ( or other @...) block are considered zombie keys. 
## To Reproduce

- Create an angular 17 project, with ngx-translate
- on the template put @if and inside its block enter a key 
- run the linter

**Comment by romanrostislavovich** [comment]
Hi @pingouin-creation ,

Can you pls show me some examples pls? 

I will try to reproduce. But on my cases lint founded keys inside of `@if` and `@for`.

**Comment by romanrostislavovich** [comment]
Hi @pingouin-creation ,

I created PR and added simple test for Angular 17. I'm not sure, but mb it's your cases. 

This task #156

**Comment by pingouin-creation** [comment]
thx it is fix right now
